name: Bug Report
description: Report a technical issue or bug
title: "[BUG]: "
labels: ["Bug", "Triage"]
projects: ["Masa Subnet"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Provide a clear technical description of the bug
      placeholder: |
        Describe:
        - What's broken
        - Impact on system/users
        - Frequency of occurrence
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce this bug
      placeholder: |
        1. Environment setup/configuration
        2. Exact steps to trigger the issue
        3. What to observe
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what should happen
      placeholder: Under normal conditions, the system should...
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Describe what actually happens
      placeholder: |
        - What went wrong
        - Error messages
        - System behavior
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Which environment is this occurring in?
      placeholder: e.g., Production, Staging, Development
    validations:
      required: true
  - type: textarea
    id: technical-context
    attributes:
      label: Technical Context
      description: Provide relevant technical details
      placeholder: |
        - System version
        - Component versions
        - Relevant logs
        - Stack trace
    validations:
      required: true
  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: If you have technical insights on the potential fix, share them here
      placeholder: Consider checking/fixing...
    validations:
      required: true
